//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Size_Supplier
    {
        public int itemId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> sizeId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
